mysite/Models/Portfolio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mysite.Models
{
    public class Portfolio
    {
        [Key]
        public int Id { get; set; }
        [Display(Name="Project Name")]
        public string Name { get; set; }
        [Display(Name="Please enter type")]
        public string Type { get; set; }
        [Display(Name="Please enter Details")]
        public string Details { get; set; }
        [Display(Name="Please enter language")]
        public string Language { get; set; }
        [Display(Name="Please enter the link")]
        public string Link { get; set; }
        [Display(Name="Please choose an image")]
        public string PortfolioPhoto { get; set; }
    }
}

mysite/ViewModels/PortfolioViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mysite.ViewModels
{
    public class PortfolioViewModel
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Project Name")]
        public string Name { get; set; }
        [Display(Name = "Please enter type")]
        public string Type { get; set; }
        [Display(Name = "Please enter Details")]
        public string Details { get; set; }
        [Display(Name = "Please enter language")]
        public string Language { get; set; }
        [Display(Name = "Please enter the link")]
        public string Link { get; set; }
        public string CurrentImage { get; set; }
        [Display(Name = "Please choose an image")]
        public IFormFile PortfolioPhoto { get; set; }
    }
}

mysite/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using mysite.Data.FileManager;
using mysite.Data.Repository;
using mysite.Models;
using mysite.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mysite.Controllers
{
    [Authorize(Roles ="Admin")]
    public class PanelController : Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;

        public PanelController(IRepository repo, IFileManager fileManager)
        {
            _repo = repo;
            _fileManager = fileManager;
        }

        public IActionResult FrontPage() 
        {
            return View();
        }

        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }

        public IActionResult Post(int id)
        {
            var post = _repo.GetPost(id);
            return View(post);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View(new PostViewModel());
            else
            {
                var post = _repo.GetPost((int)id);
                return View(new PostViewModel
                {
                    Id= post.Id,
                    Title = post.Title,
                    Body = post.Body,
                    CurrentImage = post.Image,
                    Description = post.Description,
                    Category = post.Category,
                    Tags = post.Tags
                });

            }
        }
         
        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel vm)
        {
            var post = new Post
            {
                Id = vm.Id,
                Title = vm.Title,
                Body = vm.Body,
                Description = vm.Description,
                Category = vm.Category,
                Tags = vm.Tags

            };
            if (vm.Image == null)
            {
                post.Image = vm.CurrentImage;
            }
            else
            {
                post.Image = await _fileManager.SaveImage(vm.Image);

            }

            if (post.Id > 0)
                _repo.UpdatePost(post);
            else
                _repo.AddPost(post);

            if (await _repo.SaveChangeAsync())
                return RedirectToAction("Index");
            else
                return View(post);
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repo.RemovePost(id);
            await _repo.SaveChangeAsync();
            return RedirectToAction("Index");
        }

    }
}

mysite/Controllers/PortfolioController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using mysite.Data;
using System.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using mysite.Data.FileManager;
using mysite.ViewModels;
using mysite.Models;
using mysite.Data.Repository;
using Microsoft.AspNetCore.Authorization;

namespace mysite.Controllers
{
    public class PortfolioController : Controller
    {
        private readonly IPortRepository _repo;
        private readonly IFileManager _fileManager;

        public PortfolioController(IPortRepository repo,
                                   IFileManager fileManager)
        {
            _repo = repo;
            _fileManager = fileManager;
        }


        public IActionResult Index()
        {
            var ports = _repo.GetAllPortfolios();
            return View(ports);
        }

        public ActionResult Details(int id)
        {
            var port = _repo.GetPort(id);
            return View(port);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View(new PortfolioViewModel());
            else
            {
                var port = _repo.GetPort((int)id);
                return View(new PortfolioViewModel
                {
                    Id = port.Id,
                    Name = port.Name,
                    Type = port.Type,
                    Details = port.Details,
                    Language = port.Language,
                    Link = port.Link,
                    CurrentImage = port.PortfolioPhoto
                   
                });

            }
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Edit(PortfolioViewModel vm)
        {
            var port = new Portfolio
            {
                Id = vm.Id,
                Name = vm.Name,
                Type = vm.Type,
                Details = vm.Details,
                Language = vm.Language,
                Link = vm.Link
            };
            if (vm.PortfolioPhoto == null)
            {
                port.PortfolioPhoto = vm.CurrentImage;
            }
            else 
            {
                port.PortfolioPhoto = await _fileManager.SaveImage(vm.PortfolioPhoto);
            }

                    if (port.Id > 0)
                        _repo.UpdatePortfolio(port);
                    else
                        _repo.AddPortfolio(port);

                    if (await _repo.SaveChangesAsync())
                        return RedirectToAction("Index");
                    else
                        return View(port);
 
        }


        [HttpGet("/PortfolioPhoto/{portfolioPhoto}")]
        [ResponseCache(CacheProfileName = "Monthly")]
        public IActionResult PortfolioPhoto(string portfolioPhoto)
        {
            var mine = portfolioPhoto.Substring(portfolioPhoto.LastIndexOf('.') + 1);
            return new FileStreamResult(_fileManager.ImageStream(portfolioPhoto), $"portfolioPhoto/{mine}");
        }





    }
}

mysite/Views/Portfolio/Edit.cshtml
@model PortfolioViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <form asp-controller="Portfolio" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <div class="form-group">
            <label>Name</label>
            <input class="form-control" asp-for="Name" />
        </div>
        <div class="form-group">
            <label>Type</label>
            <input class="form-control" asp-for="Type" />
        </div>
        <div class="form-group">
            <label>Details</label>
            <input class="form-control" asp-for="Details" />
        </div>
        <div class="form-group">
            <label>Language</label>
            <input class="form-control" asp-for="Language" />
        </div>
        <div class="form-group">
            <label>Link</label>
            <input class="form-control" asp-for="Link" />
        </div>
        <div class="form-group">
            <label>Image</label>
            <input class="btn btn-primary" asp-for="CurrentImage" type="hidden" />
            <input class="btn btn-info" asp-for="PortfolioPhoto" />
        </div>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />
    </form>
</div>

mysite/Views/Portfolio/Index.cshtml
@model IEnumerable<Portfolio>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/portfolio.css" rel="stylesheet" />

<!--  ======================= Start Main Area ================================ -->
    <main class="site-main">
        <!--  ======================= Project Area =============================  -->
        <section class="project-area">
            <div class="container">
                <div class="col-lg-12">
                    <div class="project-title pb-5">
                        <h1 class="text-uppercase title-h1">Recently Done Project</h1>
                        <h1 class="text-uppercase title-h1">Quality Work</h1>
                        <hr />
                    </div>
                    <ul class="filters text-center">
                        <li class="active" data-filter="*"><a href="#!">All</a></li>
                        <li data-filter=".Angular"><a href="#!">AngularApp</a></li>
                        <li data-filter=".Javascript"><a href="#!">Js templates</a></li>
                        <li data-filter=".Core"><a href="#!">Asp.net Core</a></li>
                        <li data-filter=".Data"><a href="#!">Data-tables</a></li>
                        <li data-filter=".Templates"><a href="#!">Templates</a></li>
                    </ul>
                    <div class="projects">
                        <div id="card" class="row grid justify-content-center">
                            @foreach (var port in Model)
                            {
                                    var image_path = $"/PortfolioPhoto/{port.PortfolioPhoto}";

                                    <div class="col-lg-4 item @port.Type">
                                        <div class="card">
                                            <div class="card-head">
                                                <img src="@image_path" alt="" class="img-fluid card-img">
                                                <div class="card-overlay"><h2>@port.Name</h2></div>
                                                <div class="card-hover">
                                                    <h2>Language: @port.Language</h2>
                                                    <p>Details: @port.Details</p>
                                                </div>
                                            </div>

                                            <div class="card-body text-center">
                                                <h4 class="title">@port.Name</h4>
                                                <a href="@port.Link" class="btn btn-lg card-btn">Goto Page</a>
                                            </div>
                                        </div>
                                    </div>
                            }
                         </div>

                    </div>
                    <!--<div class="container-fluid">
                        <div class="table-responsive">
                            <table class="table table-stripped table-hover">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Type</th>
                                        <th>Detail</th>
                                        <th>Language</th>
                                        <th>Link</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var port in Model)
                                    {
                                    <tr>
                                        <td>@port.Id</td>
                                        <td>@port.Name</td>
                                        <td>@port.Type</td>
                                        <td>@port.Details</td>
                                        <td>@port.Language</td>
                                        <td>@port.Link</td>
                                        <td>
                                            <a asp-controller="Panel" asp-action="Edit" asp-route-id="@port.Id">
                                                Edit
                                            </a>
                                        </td>
                                        <td>
                                            <a asp-controller="Panel" asp-action="Remove" asp-route-id="@port.Id">
                                                Remove
                                            </a>
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>-->
                    <!-- /#page-content-wrapper -->
                </div>
            </div>
        </section>
        <!--  ======================= End Project Area =============================  -->
    </main>
<!--  ======================= End Main Area ================================ -->
@section Scripts{
    <script src="~/lib/js/portfolio.js"></script>
     
}