mysite/Models/Home.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mysite.Models
{
    public class Home
    {
        public int Id { get; set; }

        public string Title { get; set; } = "";

        public string Name { get; set; } = "";

        public string Service { get; set; } = "";

        public string Description { get; set; } = "";

        public string Email { get; set; } = "";

        public string PhoneNumber { get; set; } = ""; 

        public DateTime LastUpdated { get; set; } = DateTime.Now;
    }
}

mysite/ViewModels/HomeViewModel.cs
using mysite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mysite.ViewModels
{
    public class HomeViewModel
    {
        public Home Home { get; set; }
    }
}

mysite/Controllers/Api/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mysite.Data;
using mysite.Models;

namespace mysite.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class HomeController : ControllerBase
    {
        private readonly DataContext _context;

        public HomeController(DataContext context)
        {
            _context = context;
        }

        // GET: api/Home
        [HttpGet]
        public IEnumerable<Home> GetHome()
        {
            return _context.Home;
        }

        // GET: api/Home/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetHome([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var home = await _context.Home.FindAsync(id);

            if (home == null)
            {
                return NotFound();
            }

            return Ok(home);
        }

        // PUT: api/Home/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutHome([FromRoute] int id, [FromBody] Home home)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != home.Id)
            {
                return BadRequest();
            }

            _context.Entry(home).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HomeExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Home
        [HttpPost]
        public async Task<IActionResult> PostHome([FromBody] Home home)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _context.Home.Add(home);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetPost", new { id = home.Id }, home);
        }

        // DELETE: api/Home/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteHome([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var home = await _context.Home.FindAsync(id);
            if (home == null)
            {
                return NotFound();
            }

            _context.Home.Remove(home);
            await _context.SaveChangesAsync();

            return Ok(home);
        }

        private bool HomeExists(int id)
        {
            return _context.Home.Any(e => e.Id == id);
        }


    }
}

mysite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mysite.Data;
using mysite.Models;
using mysite.ViewModels;

namespace mysite.Controllers
{
    public class HomeController : Controller
    {
        private DataContext _context;

        public HomeController(DataContext context)
        {
            _context = context;
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Gallery()
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            var home = _context.Home.SingleOrDefault(h => h.Id == id);
    
            var viewModel = new HomeViewModel
            {
                Home = home
            };
            return View("HomeForm", viewModel);
        }

        public ActionResult New()
        {
            var viewModel = new HomeViewModel
            {
                Home = new Home()
              
            };

            return View("HomeForm", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Home home)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new HomeViewModel
                {
                    Home = home
                };
                return View("HomeForm", viewModel);
            }

            if (home.Id == 0)
                _context.Home.Add(home);
            else
            {
                var homeInDb = _context.Home.Single(c => c.Id == home.Id);
                homeInDb.Title = home.Title;
                homeInDb.Name = home.Name;
                homeInDb.Service = home.Service;
                homeInDb.Description = home.Description;
                homeInDb.Email = home.Email;
                homeInDb.PhoneNumber = home.PhoneNumber;
                
            }
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");


        }


        public IActionResult HomeEdit()
        {
            return View();
        }

        public IActionResult YouTube()
        {
            return View();
        }

        public IActionResult MyVideos() 
        {

            return View();
        }

    }
}

mysite/Controllers/MyMessagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using mysite.Data;
using mysite.Models;
using mysite.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mysite.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MyMessagesController : Controller
    {
        private DataContext _context;

        public MyMessagesController(DataContext context)
        {
            _context = context;
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

      
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult New()
        {
            var viewModel = new MyMessagesViewModel(); 
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Create(MyMessage mymessage)
        {
            _context.MyMessages.Add(mymessage);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

    }
}

mysite/Controllers/PortfolioController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using mysite.Data;
using System.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using mysite.Data.FileManager;
using mysite.ViewModels;
using mysite.Models;
using mysite.Data.Repository;
using Microsoft.AspNetCore.Authorization;

namespace mysite.Controllers
{
    public class PortfolioController : Controller
    {
        private readonly IPortRepository _repo;
        private readonly IFileManager _fileManager;

        public PortfolioController(IPortRepository repo,
                                   IFileManager fileManager)
        {
            _repo = repo;
            _fileManager = fileManager;
        }


        public IActionResult Index()
        {
            var ports = _repo.GetAllPortfolios();
            return View(ports);
        }

        public ActionResult Details(int id)
        {
            var port = _repo.GetPort(id);
            return View(port);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View(new PortfolioViewModel());
            else
            {
                var port = _repo.GetPort((int)id);
                return View(new PortfolioViewModel
                {
                    Id = port.Id,
                    Name = port.Name,
                    Type = port.Type,
                    Details = port.Details,
                    Language = port.Language,
                    Link = port.Link,
                    CurrentImage = port.PortfolioPhoto
                   
                });

            }
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Edit(PortfolioViewModel vm)
        {
            var port = new Portfolio
            {
                Id = vm.Id,
                Name = vm.Name,
                Type = vm.Type,
                Details = vm.Details,
                Language = vm.Language,
                Link = vm.Link
            };
            if (vm.PortfolioPhoto == null)
            {
                port.PortfolioPhoto = vm.CurrentImage;
            }
            else 
            {
                port.PortfolioPhoto = await _fileManager.SaveImage(vm.PortfolioPhoto);
            }

                    if (port.Id > 0)
                        _repo.UpdatePortfolio(port);
                    else
                        _repo.AddPortfolio(port);

                    if (await _repo.SaveChangesAsync())
                        return RedirectToAction("Index");
                    else
                        return View(port);
 
        }


        [HttpGet("/PortfolioPhoto/{portfolioPhoto}")]
        [ResponseCache(CacheProfileName = "Monthly")]
        public IActionResult PortfolioPhoto(string portfolioPhoto)
        {
            var mine = portfolioPhoto.Substring(portfolioPhoto.LastIndexOf('.') + 1);
            return new FileStreamResult(_fileManager.ImageStream(portfolioPhoto), $"portfolioPhoto/{mine}");
        }





    }
}

mysite/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<style>

.tabs{
    width:90%;
    height:auto;
    margin:0 auto;
}

/* tab list item */
.tabs .tabs-list{
    list-style:none;
    margin:0px;
    padding:0px;
}
.tabs .tabs-list li{
    width:100px;
    float:left;
    margin:0px;
    margin-right:2px;
    padding:10px 5px;
    text-align: center;
    background-color:cornflowerblue;
    border-radius:3px;
}
.tabs .tabs-list li:hover{
    cursor:pointer;
}
.tabs .tabs-list li a{
    text-decoration: none;
    color:white;
}

/* Tab content section */
.tabs .tab{
    display:none;
    width:96%;
    min-height:250px;
    height:auto;
    border-radius:3px;
    padding:20px 15px;
    background-color:lavender;
    color:darkslategray;
    clear:both;
}
.tabs .tab h3{
    border-bottom:3px solid cornflowerblue;
    letter-spacing:1px;
    font-weight:normal;
    padding:5px;
}
.tabs .tab p{
    line-height:20px;
    letter-spacing: 1px;
}

/* When active state */
.active{
    display:block !important;
}
.tabs .tabs-list li.active{
    background-color:lavender !important;
    color:black !important;
}
.active a{
    color:black !important;
}


</style>

<div class="container mt-4">
    <div class="row">
        <h1>Martin's Profile</h1>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="card">
                <img class="card-img-top img-thumbnail" src="~/images/admin/me.jpg" alt="{{user.knownAs}}">
                <div class="card-body">
                    <div>
                        <strong>Location:</strong>
                        <p class="text-dark">Orlando, Florida</p>
                    </div>
                    <div>
                        <strong>Title:</strong>
                        <p class="text-dark">
                            FullStack-
                            <span class="text-primary">Developer</span>
                        </p>
                    </div>
                    <div class="social-icons">
                        <a class="social-icon" href="#"><i class="fa fa-linkedin"></i></a>
                        <a class="social-icon" href="#"><i class="fa fa-github"></i></a>
                        <a class="social-icon" href="#"><i class="fa fa-twitter"></i></a>
                        <a class="social-icon" href="#"><i class="fa fa-facebook-f"></i></a>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="btn-group d-flex">
                        <a class="btn btn-primary w-100" asp-area="" asp-controller="Portfolio" asp-action="Index">Check Out My Projects ...</a>
                        <a class="btn btn-success w-100" asp-area="" asp-controller="MyMessages" asp-action="New">Message</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="tabs">
                <ul class="tabs-list">
                    <li class="active"><a href="#tab1">About</a></li>
                    <li><a href="#tab2">Expertise</a></li>
                    <li><a href="#tab3">Technologies</a></li>
                </ul>
                <div id="tab1" class="tab active">
                    <h3 class="text-uppercase pt-5">Hi! Let me introduce myself, I'm Martin.</h3>
                    <div class="paragraph py-4">
                        <p class="para">
                            Am Entrepreneur and love coming out with new Ideas, and pursuit new opportunities.
                            My role as Asp.Net Developer is Producing code with .Net Framework (C#), I develop and write high-quality code, design, test,
                            maintain and support custom mobile and web applications, and most importante meet
                            customer requirements.
                        </p>
                    </div>
                </div>
                <div id="tab2" class="tab">
                    <!-- Page Content-->
                    <div class="container-fluid p-0">
                        <!-- toggle area -->
                        <section id="gallery">
                            <div class="accordion container">
                                <div class="row">
                                    <div class="col-lg-12 text-center">
                                        <h2>I Love Working With</h2>
                                        <hr>
                                    </div>
                                    <button class="accordion"><h3>Web Development.....</h3>Click Here For More Info</button>
                                    <div class="panel">
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <img src="~/images/accordion/web-development.jpg" class="img-fluid">
                                                </div>
                                                <div class="col-sm-6">
                                                    <h2>We can create any Page for you</h2>
                                                    <p class="text-black-50">We animate any web page and we organized your files</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <button class="accordion"><h3>Software Developement......</h3>Click Here For More Info</button>
                                    <div class="panel">
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <img src="~/images/accordion/software-developer.jpg" class="img-fluid">
                                                </div>
                                                <div class="col-sm-6">
                                                    <h2>We can create any Page for you</h2>
                                                    <p class="text-black-50">We animate any web page and we organized your files</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <button class="accordion"><h3>FullStack Developement.....</h3>Click Here For More Info</button>
                                    <div class="panel">
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <img src="~/images/accordion/FullStack.jpg" class="img-fluid">
                                                </div>
                                                <div class="col-sm-6">
                                                    <h2>We can create any Page for you</h2>
                                                    <p class="text-black-50">We animate any web page and we organized your files</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
                <div id="tab3" class="tab">
                    <h3>My favorite languages</h3>
                    <ul class="list-group">
                        <li class="list-group-item">C#</li>
                        <li class="list-group-item">Angular</li>
                        <li class="list-group-item">Html 5</li>
                        <li class="list-group-item">Css</li>
                        <li class="list-group-item">Javascript</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


    <!--  ======================== End Brand Area ==============================  -->
    <!--  ======================= End Main Area ================================ -->

    @section Scripts{
        <script src="~/lib/js/accordion.js"></script>
        <script src="~/lib/js/script.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {

                $(".tabs-list li a").click(function (e) {
                    e.preventDefault();
                });

                $(".tabs-list li").click(function () {
                    var tabid = $(this).find("a").attr("href");
                    $(".tabs-list li,.tabs div.tab").removeClass("active");   // removing active class from tab

                    $(".tab").hide();   // hiding open tab
                    $(tabid).show();    // show tab
                    $(this).addClass("active"); //  adding active class to clicked tab

                });

            });
        </script>
    }

mysite/Views/Home/Gallery.cshtml
@{ ViewData["Title"] = "Gallery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- =========================== Thumbnail Gallery ========================================== -->
<section id="thumbgallery" class="bg-dark">
    <div class="text-center">
        <h2 class='text-white font-weight-bold'>let's get started with weight loss</h2>
        <h2 class="font-weight-bold">Better design and tips</h2>
        <p class="font-weight-bold">Better experiences.</p>
        <a asp-area="" asp-controller="MyMessages" asp-action="New" class="btn btn-lg btn-rounded btn-primary">Send Message</a><br>
    </div>
    <div class="container">
        <div class="main-img">
            <img src="~/images/img/img1.jpeg" id="current" />
        </div>
        <div class="imgs">
            <img src="~/images/img/img1.jpeg" />
            <img src="~/images/img/img2.jpeg" />
            <img src="~/images/img/img3.jpeg" />
            <img src="~/images/img/img4.jpeg" />
            <img src="~/images/img/img5.jpeg" />
            <img src="~/images/img/img6.jpeg" />
            <img src="~/images/img/img7.jpeg" />
            <img src="~/images/img/img8.jpeg" />
        </div>
    </div>
</section>


<section id="card-area">
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h2>Template <small>Core Features</small></h2>
                    <hr />
                </div>
            </div>
        </div>
        <div id="card" class="row"></div>
    </div>
</section>
<!--  ======================== Testimonials About Me Area ==============================  -->
<section class="testimonials bg-info">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-12">
                <div class="about-title">
                    <h1>Client Say about me</h1>
                    <p class="para text-center">
                        Subscribe easy tutorials channel to wacth more videos
                    </p>
                </div>
            </div>
        </div>
        <div id="owl-demo">
            <div class="item">
                <div class="inner">
                    <div class="row">
                        <div class="card col-lg-6 col-xs-12 ml-md-5">
                            <img class="img-fluid circle user" src="~/images/testimonials/t1.jpg" alt="img1">
                        </div>
                        <div class="card-body">
                            <p class="testimonial">
                                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem architecto
                                consequuntur ratione, obcaecati corrupti deserunt.
                            </p>
                            <h4 class="text-uppercase">Kevin Martin</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="inner">
                    <div class="row">
                        <div class="card col-lg-6 col-xs-12 ml-md-5">
                            <img class="img-fluid circle user" src="~/images/testimonials/t2.jpg" alt="img1">
                        </div>
                        <div class="card-body">
                            <p class="testimonial">
                                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem architecto
                                consequuntur ratione, obcaecati corrupti deserunt.
                            </p>
                            <h4 class="text-uppercase">Kevin Martin</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="inner">
                    <div class="row">
                        <div class="card col-lg-6 col-xs-12 ml-md-5">
                            <img class="img-fluid circle user" src="~/images/testimonials/t1.jpg" alt="img1">
                        </div>
                        <div class="card-body">
                            <p class="testimonial">
                                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem architecto
                                consequuntur ratione, obcaecati corrupti deserunt.
                            </p>
                            <h4 class="text-uppercase">Kevin Martin</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="inner">
                    <div class="row">
                        <div class="card col-lg-6 col-xs-12 ml-md-5">
                            <img class="img-fluid circle" src="~/images/testimonials/t2.jpg" alt="img1">
                        </div>
                        <div class="card-body">
                            <p class="testimonial">
                                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem architecto
                                consequuntur ratione, obcaecati corrupti deserunt.
                            </p>
                            <h4 class="text-uppercase">Kevin Martin</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="inner">
                    <div class="row">
                        <div class="card col-lg-6 col-xs-12 ml-md-5">
                            <img class="img-fluid circle" src="~/images/testimonials/t1.jpg" alt="img1">
                        </div>
                        <div class="card-body">
                            <p class="testimonial">
                                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem architecto
                                consequuntur ratione, obcaecati corrupti deserunt.
                            </p>
                            <h4 class="text-uppercase">Kevin Martin</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="inner">
                    <div class="row">
                        <div class="card col-lg-6 col-xs-12 ml-md-5">
                            <img class="img-fluid circle" src="~/images/testimonials/t2.jpg" alt="img1">
                        </div>
                        <div class="card-body">
                            <p class="testimonial">
                                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem architecto
                                consequuntur ratione, obcaecati corrupti deserunt.
                            </p>
                            <h4 class="text-uppercase">Kevin Martin</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--  ======================== End About Me Area ==============================  -->
<!--  ========================== Subscribe me Area ============================  -->
<div class="bg-faded pt90 pb90">
    <div class="container">
        <div class="title-heading1 mb50">
            <h3>Subscribe to our newsletter</h3>
        </div>
        <div class="row">
            <div class="col-lg-6 mr-auto ml-auto">
                <form id="widget-subscribe-form" action="index.html" role="form" method="post" class="mb0">
                    <div class="input-group input-group-lg">

                        <input type="email" name="widget-subscribe-form-email" class="form-control required" placeholder="Enter your Email">
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit">Subscribe</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!--  ====================== End Services Area =============================  -->
<section id="contact" class="bg-lightblue mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center">
                <h2 class="section-heading">Let's Get In Touch!</h2>
                <hr class="my-4">
                <p class="mb-5">Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 ml-auto text-center">
                <i class="fa fa-phone fa-3x mb-3 sr-contact-1"></i>
                <p>863-969-8248</p>
            </div>
            <div class="col-lg-4 mr-auto text-center">
                <i class="fa fa-envelope fa-3x mb-3 sr-contact-2"></i>
                <p>
                    <a href="mailto:electronicsmf@aol.com">Electronicsmf@aol.com</a>
                </p>
            </div>
        </div>
    </div>
</section>
<!--  ========================== End Subscribe me Area ============================  -->
<section class="hours parallax--bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Hours</h2>
                <hr>
                <p>Monday-Friday: 7:30 am - 6:00 pm<p>
                    <hr>
                <p>Saturday: 7:30 am - noon</p>
                <hr>
            </div>
        </div>
    </div>
</section>
<!-- footer-area -->
@section Scripts {
    <script src="~/lib/js/owl.js"></script>
    <script src="~/lib/js/repairs.js"></script>
    <script src="~/lib/js/gallery.js"></script>
}

mysite/Views/Home/MyVideos.cshtml
@{
    ViewData["Title"] = "MyVideos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
      background-color: #eee;
    }
    #container {
       width: 560px;
       height:500vh;
       background-color: #fff;
       margin: 0 auto;
    }
    header, 
    section{
      text-align:center;
      width:560px;
      background-color:#fff;
    }
    section{
      top:60px;
    }
    .logo {
      width:120px;
      padding:10px;
    }
    main {
      padding:370px 18px 10px;
    }
    .thumb {
     height: 70px;
    }

</style>
<div class="container">
            <div class="row">
                <div class="col-lg-12">
                        <img src="~/images/youtube.png" class="logo" />
                </div>
            </div>  
            <div class="row">
                <div class="col-lg-12">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Y4zQQpRCwUY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <img src="https://www.youtube.com/embed/Y4zQQpRCwUY" alt="Alternate Text" class="thumb" />
                    <div class="details">
                        <h4>Title</h4>
                        <p>Iam a description</p>
                    </div>
                </div>
            </div>
 </div>